import { db, markersTable } from "@workspace/db";
import { count, eq, inArray, sql } from "drizzle-orm";
import { logger } from "./lib/logger";

// Entries removed from the curated list — deleted from DB on every boot
const REMOVED_FROM_SEED: string[] = [
  "Heyday Cafe",              // permanently closed
  "The Farm Table",           // permanently closed (Jan 2026)
  "Cascada",                  // permanently closed (March 2025)
  "Smith Flat House",         // dining room closed Jan 31 2026; events-only venue
  "Jodar Vineyards & Winery", // permanently closed
  "Latcham Vineyards",        // permanently closed
  "Fitzpatrick Winery & Lodge", // permanently closed
  "Lava Cap Wine Bar & Bistro", // no evidence this location exists
  "Kids Inc. Apple Ranch",    // no confirmed 2025 operating information
  "Argonaut Farm to Fork Cafe", // renamed — replaced by "Argonaut Coffee & Provisions"
];

const SEED_DATA = [
  // ── WINERIES: EL DORADO AVA ───────────────────────────────────────────────
  { name: "Boeger Winery", city: "Placerville", note: "The benchmark. Greg Boeger planted the first vines in 1972, making this the oldest producing winery in El Dorado County. Planted on a historic Gold Rush homestead on Carson Road, the property has its own 1872 pear orchard still bearing fruit. The Barbera and Zinfandel are grown at 2,600 feet on decomposed granite. Tasting room open daily — walk-ins welcome, no appointment needed. This is where El Dorado mountain viticulture begins.", category: "winery", lat: 38.7207, lng: -120.6884, website: "https://www.boegerwinery.com" },
  { name: "Lava Cap Winery", city: "Placerville", note: "Family estate on Fruitridge Road at 2,600 feet. The volcanic basalt soils here — the 'lava cap' — drain fast and stress the vines just enough. Barbera, Zinfandel, Petite Sirah, and a Muscat that earns its place. Tasting room open Thu–Mon with sweeping views into the valley. The Petite Sirah is among the most structured in the county.", category: "winery", lat: 38.7440, lng: -120.6729, website: "https://www.lavacap.com" },
  { name: "Madrona Vineyards", city: "Camino", note: "Three family-owned vineyards at mountain elevation — one in Apple Hill, two in Pleasant Valley — producing an unusually wide range of Rhône and Bordeaux varietals. Winemakers Paul and Maggie Bush. The Dry Riesling is a signature; the Tempranillo and Viognier are equally serious. Own-rooted vines in deep Aiken clay loam soils. Sit-down tasting experiences with reservations recommended. The most complete estate experience in El Dorado County.", category: "winery", lat: 38.7068, lng: -120.6258, website: "https://www.madronavineyards.com" },
  { name: "Holly's Hill Vineyards", city: "Placerville", note: "The Rhône specialists of El Dorado County. Planted entirely to Rhône varieties — Grenache, Syrah, Mourvèdre, Counoise, Roussanne, Viognier — on decomposed granite at 2,700 feet. Co-winemaker and brewer Josh also makes artisanal craft beers on site, including experimental hybrids. The Patriarche Rhône blend is a regional benchmark — Mourvedre, Syrah, Grenache, Counoise together. The best combination of winery, brewery, and food in the county.", category: "winery", lat: 38.5938, lng: -120.7044, website: "https://www.hollyshill.com" },
  { name: "Narrow Gate Vineyards", city: "Placerville", note: "The most philosophically compelling winery in El Dorado County. The entire 86-acre farm is Demeter-certified biodynamic — certified since 2010, organic since 2007. Winemaker Frank Hildebrand composts from grape skins, cow manure, and biodynamic preparations. Whole-berry fermentation, native yeasts, hand punch-downs. The tasting room is a candlelit cellar with outdoor patio, cheese and charcuterie boards, and seasonal pairing events. Seek the Syrah-Viognier co-ferment and port-style Chocolate Splash. The Slow Food ideal in a bottle.", category: "winery", lat: 38.5847, lng: -120.6867, website: "https://www.narrowgatevineyards.com" },
  { name: "Miraflores Winery", city: "Placerville", note: "Estate vineyard on Four Springs Trail at 2,200 feet, planted on a historic apple orchard site. Known for Spanish varieties — Tempranillo, Garnacha, Monastrell — alongside mountain Zinfandel and Barbera. Small-production, family-run, and one of the quieter gems in the El Dorado AVA. The cellar cave tastings are worth booking.", category: "winery", lat: 38.7095, lng: -120.6971, website: "https://www.mirafloreswinery.com" },
  { name: "Gold Hill Vineyard", city: "Placerville", note: "Estate winery on Vineyard Lane at 2,400 feet, with a separate farmstand carrying wine, olive oil, and vineyard eggs. The Zinfandel is planted on old vines with granitic loam soils. A working farm that also makes wine — the format here rewards lingering. One of the friendliest stops in the El Dorado AVA corridor.", category: "winery", lat: 38.6982, lng: -120.7003, website: "https://www.goldhillvineyard.com" },
  { name: "Sierra Vista Vineyards", city: "Placerville", note: "Forty-plus-year estate on Pleasant Valley Road at 2,900 feet — one of the highest-elevation tasting rooms in El Dorado County. The Rhône program here is serious: Syrah, Viognier, Grenache, and a Syrah-Grenache blend that shows what Fair Play-adjacent elevations can do. Walk-in tastings available weekends; check the calendar for harvest events.", category: "winery", lat: 38.6140, lng: -120.6915, website: "https://www.sierravistawinery.com" },
  { name: "Chateau Davell", city: "Camino", note: "Founded by Eric and Davell Hays on the Carson Road corridor. Handcrafted small-lot wines using sustainable vineyard management and old-world technique. Specializes in French-inspired cuisine small bites paired with wines, particularly at Passport Weekend events. Popular event venue with live music Fridays from May through October.", category: "winery", lat: 38.7097, lng: -120.6540, website: "https://eldoradowines.org" },
  { name: "Crystal Basin Cellars", city: "Camino", note: "Part of the Carson Road Wineries collective — an informal affiliation of six family-owned, small-production wineries along Carson Road between Placerville and Camino. Open daily 11am–5pm. A practical starting point for first-time visitors who want to cover multiple estates in one corridor without driving all over the county.", category: "winery", lat: 38.7090, lng: -120.6553, website: "https://www.crystalbasin.com" },
  { name: "Toogood Estate Winery", city: "Somerset", note: "Two distinct tasting experiences: the sprawling Fair Play estate on Fairplay Road and a conveniently located downtown Placerville tasting room. Girl Scout Cookie pairings in February are a perennial sellout. Solid range of Rhône and Bordeaux varietals at both locations. Estate open daily 11am–6pm; downtown Thurs–Mon 1–8pm.", category: "winery", lat: 38.6055, lng: -120.7092, website: "https://www.toogoodwinery.com" },
  { name: "David Girard Vineyards", city: "Placerville", note: "Located near Coloma in the South Fork American River Valley — a scenic setting outside the usual Apple Hill and Fair Play corridors. Elegant, food-oriented wines made for the table. Weekend tastings Fri–Sun 11am–5pm; plan ahead as the drive requires intention. A quieter, more intimate discovery than the main wine trail stops.", category: "winery", lat: 38.8018, lng: -120.8822, website: "https://www.davidgirardvineyards.com" },
  { name: "Nello Olivo Winery", city: "Placerville", note: "Award-winning wines made with winemaker Marco Cappelli — food-friendly, well-balanced, and consistently decorated at competition. Two locations: a historic Sequoia Mansion tasting room downtown and a second site in Camino. The annual 'Godfather Experience' at Passport Weekend — 10 wines paired with Italian bites, costumed staff, themed music — is one of the event's most talked-about activations.", category: "winery", lat: 38.7291, lng: -120.7978, website: "https://eldoradowines.org" },
  { name: "Starfield Vineyards & Winery", city: "Placerville", note: "Boutique winery in the heart of Apple Hill with full food service — light bites, lunch, and dinner by reservation until 7pm. Mountain views, outdoor dining, and consistently reviewed as one of the best winery dining experiences in the county. Daily 11am–5pm; dinner until 7pm by reservation. Sat–Sun reservations recommended.", category: "winery", lat: 38.7134, lng: -120.6395, website: "https://www.starfieldvineyards.com" },
  { name: "Lewis Grace Winery", city: "Placerville", note: "Family operation led by retired surgeon Steve Grace; sons Tyler and Trevor are the winemakers. Descendants of a Revolutionary War patriot — and the family heritage is woven into the label. Over 25 award-winning wines including Rosé, Petit Sirah, and Mourvèdre. Open daily 11am–5pm on Carson Road.", category: "winery", lat: 38.7132, lng: -120.6408, website: "https://www.gracepatriotwines.com" },

  // ── WINERIES: FAIR PLAY AVA ───────────────────────────────────────────────
  { name: "Cedarville Vineyard", city: "Somerset", note: "Jonathan and Susan Lacey's estate on Fair Play Road — a reference point for what this high-elevation appellation can produce. Syrah, Grenache, Zinfandel, and Viognier from dry-farmed organically managed vines. Appointment-only tastings; small allocation. One of the wines people drive to Fair Play specifically to find.", category: "winery", lat: 38.5892, lng: -120.6880, website: "https://cedarvillevineyard.com" },
  { name: "Skinner Vineyards", city: "Somerset", note: "Fair Play AVA estate named for the Skinner family who farmed this land during the Gold Rush. The winery revives that heritage with mountain Zinfandel, Barbera, and Rhône-style blends. The tasting room has views across the appellation and the team pours honestly — no upsell, just wine. Check the event calendar for barrel tastings and harvest dinners.", category: "winery", lat: 38.5968, lng: -120.7128, website: "https://www.skinnervineyards.com" },
  { name: "Windwalker Vineyard & Winery", city: "Somerset", note: "Twenty-plus-acre estate at 2,500 feet on Perry Creek Road. Mountain Zinfandel and Rhône-style wines made from estate-grown fruit. The Gold Rush Gold blend and Zinfandel are consistent performers. Tasting room open Thu–Sun; the setting is quiet and genuinely beautiful in harvest season.", category: "winery", lat: 38.5899, lng: -120.6992, website: "https://windwalkerwinery.com" },
  { name: "Mellowood Vineyard", city: "Somerset", note: "Owned and operated by a Kenyan transplant winemaker in the Fair Play AVA — one of the most distinctive producer stories in the entire Sierra Foothills. Award-winning wines paired with KK's Kenyan BBQ and Kachumbari salad prepared with imported East African spices on beautiful patios overlooking the oak grove and vineyard. Genuinely unusual and worth making the drive to Fair Play specifically for.", category: "winery", lat: 38.5921, lng: -120.7155, website: "https://eldoradowines.org" },
  { name: "Bumgarner Winery", city: "Somerset", note: "Small-production estate with on-site lodging rental at the Fair Play location. Two tasting rooms: Fair Play Fri–Sun 12–4pm and a Camino location daily 11am–5pm. Excellent service and reasonable price point consistently cited by visitors. A good base if you're spending a night in the AVA.", category: "winery", lat: 38.5940, lng: -120.7183, website: "https://www.bumgarnerwinery.com" },
  { name: "Cantiga Winery", city: "Somerset", note: "Boutique Rhône varietal specialist in the Fair Play AVA on Meyers Lane. Open Fri–Sun 11am–5pm. Focused entirely on the Rhône palette — the kind of small-production winery that rewards the detour off the main Fair Play Road corridor.", category: "winery", lat: 38.6012, lng: -120.7252, website: "https://www.cantigawine.com" },
  { name: "Medeiros Family Wines", city: "Somerset", note: "Small-production family operation on Fairplay Road. Live music and barrel tastings with small bite pairings are featured at Passport Weekend. Open Fri–Sun 11am–5pm. One of the Fair Play AVA's convivial weekend stops, best when visited as part of a full-day southern loop.", category: "winery", lat: 38.5951, lng: -120.7163, website: "https://www.medeirosfamilywines.com" },
  { name: "E16 Winery", city: "Somerset", note: "Estate winery on Perry Creek Road in the Fair Play AVA. Open Fri–Sun 11am–5pm. Named for the elevation corridor where the vines grow — a straightforward label for a winery focused on mountain terroir over marketing.", category: "winery", lat: 38.5831, lng: -120.6881, website: "https://www.e16winery.com" },
  { name: "Kehret Vineyards", city: "Somerset", note: "Purchased and reopened in 2019 with winemaker Steve Leveque at the helm — formerly a decade at Robert Mondavi. Limited-production, handcrafted wines showcasing mountain-top terroir on Tower Road in the Fair Play AVA. Open Fri–Sun 11am–5pm. A newer operation worth tracking as the team hits its stride.", category: "winery", lat: 38.6017, lng: -120.7097, website: "https://www.kehretvineyards.com" },
  { name: "Gwinllan Estate", city: "Somerset", note: "The sparkling wine specialist of the Fair Play AVA — a Welsh-named estate on Fairplay Road making Blanc de Noirs, Brut, and a late-disgorged sparkling that has won Best Sparkling at the Foothill Wine Competition four consecutive years. A genuinely rare thing: serious, traditional-method sparkling wine made at elevation in the Sierra foothills. Small production, appointment-preferred, and worth planning ahead for.", category: "winery", lat: 38.6125, lng: -120.6958, website: "https://www.gwinllanestate.com" },
  { name: "Cielo Sulla Terra", city: "Somerset", note: "Italian-inspired estate on Perry Creek Road — 'sky above the earth,' planted with Primitivo (a Zinfandel clone), Sangiovese, Barbera, and Vermentino. The 2024 Rosé of Primitivo 'Primarosa' won Best of Show at the Foothill Wine Competition 2025. Thoughtfully made small-production wines from a family that takes the Italian-Californian connection seriously. Open Fri–Sun, 8061 Perry Creek Rd.", category: "winery", lat: 38.5828, lng: -120.6855, website: "https://cielosullaterra.com" },
  { name: "Element 79 Vineyards", city: "Somerset", note: "Fair Play AVA estate at 2,400 feet on Fairplay Road — consistently one of the top-rated wineries in El Dorado County. Open seven days a week (11am–5pm, Mon–Wed from noon), which makes it one of the most accessible tasting rooms in the AVA. A well-regarded stop for visitors who want to spend a full week in the Fair Play wine country without planning around weekend-only hours.", category: "winery", lat: 38.6040, lng: -120.7100, website: "https://www.element79vineyards.com" },
  { name: "Saluti Cellars", city: "Somerset", note: "A hidden gem tucked into a 250-acre canyon on Grizzly Flat Road in the heart of the Fair Play AVA. Owner Randy Rossi makes small-production wines in a setting that feels genuinely off the beaten path — the canyon and the views reward the extra miles on the back roads. Open Sat–Sun 11am–5pm. One of those wineries that regulars keep to themselves.", category: "winery", lat: 38.6334, lng: -120.6242, website: "https://www.saluticellars.com" },
  { name: "Château d'Estienne", city: "Somerset", note: "Boutique estate winery on Omo Ranch Road in the Fair Play AVA — the tasting room sits atop a hill with exceptional views of the Sierra Foothills. Small-production, Fri–Sun 11am–5pm (Fri and Sun close at 4pm). One of the Fair Play AVA's more scenic stops, worth timing for a clear day when the mountain views open up behind the vines.", category: "winery", lat: 38.6050, lng: -120.7030, website: "https://chateaudestienne.com" },
  { name: "Busby Cellars", city: "Somerset", note: "Small family-owned vineyard and boutique winery on Grizzly Flat Road — the northernmost winery in the Fair Play AVA. Special attention throughout the growing and winemaking process to craft elegant wines that marry varietal characteristics with mountain terroir. A quiet, personal tasting experience on the back road that connects Fair Play with the Grizzly Flat corridor.", category: "winery", lat: 38.6350, lng: -120.6500, website: "https://busbycellars.com" },
  { name: "diVittorio Winery", city: "Camino", note: "A family winery on Carson Road continuing a tradition that began when the diVittorio family immigrated from Italy in 1904. The tasting room carries both traditional estate wines and something genuinely unusual: wines made from nectarines and plums harvested from the property's own orchard, alongside Portuguese Port and Orange Muscat. Open Fri–Sun 11am–5pm. The most distinctive wine portfolio on the Carson Road corridor.", category: "winery", lat: 38.7091, lng: -120.6552, website: "https://divittoriowinery.com" },
  { name: "José Wine Caves", city: "Garden Valley", note: "A family-owned boutique winery in Garden Valley, north of Placerville on the Hwy 193 corridor — the tasting room is built into natural wine caves overlooking the historic Coloma Valley. Founded by the Elena family. Hand-tended vines, cool cave aging, and a setting unlike anything else in El Dorado County. Open Sat–Sun 10am–5pm. Worth the drive north if you want a genuinely different wine country experience.", category: "winery", lat: 38.8485, lng: -120.8290, website: "https://josewinecaves.com" },

  // ── APPLE HILL / FARMSTANDS ───────────────────────────────────────────────
  { name: "High Hill Ranch", city: "Camino", note: "The iconic Apple Hill destination — 60-plus apple varieties on a 40-acre ranch at 3,000 feet on High Hill Road. Fresh-pressed cider, apple pies, caramel apples, and a petting zoo. The crowds on October weekends are real — arrive before 10 AM. Open late July through December; peak season August through November. One of the most visited destinations in El Dorado County.", category: "farmstand", lat: 38.7070, lng: -120.6258, website: "https://www.highhillranch.com" },
  { name: "Boa Vista Orchards", city: "Placerville", note: "One of Apple Hill's oldest farms — 50-plus apple varieties, pears, Asian pears, and a full farm store on Carson Road. Known for exceptional fresh apple cider, homemade pies, and the kind of farm stand that hasn't been sanitized for tourism. The gift shop carries local honeys and jams. Open August through December.", category: "farmstand", lat: 38.7126, lng: -120.6408, website: "https://www.boavistaorchards.com" },
  { name: "Rainbow Orchards", city: "Camino", note: "U-pick apples on Larsen Drive — Galas, Fujis, Jonagolds, and heirloom varieties on a working family orchard. The u-pick experience here is genuine: you bag your own fruit, weigh it at the barn. Cider doughnuts on weekends. A good choice when you want to pick your own rather than buying from a farm store. Open late August through December.", category: "farmstand", lat: 38.7150, lng: -120.6315, website: "https://www.rainboworchards.net" },
  { name: "Abel's Acres", city: "Camino", note: "Small family apple farm on Larsen Drive — Galas, Fujis, Braeburns, Honeycrisps, and Jonagolds plus a seasonal pumpkin patch. No crowds, no Instagram moments — just a working orchard on a back road. Call ahead. Open weekends late August through October.", category: "farmstand", lat: 38.7152, lng: -120.6280, website: "https://www.applebill.com" },
  { name: "Denver Dan's", city: "Placerville", note: "Apple Hill classic on Carson Road — caramel apples, fresh-pressed cider, apple butter, and pies. Unpretentious, generous, and reliably good. A consistent stop on the Apple Hill loop when you want to stock the car before heading back down the mountain. Open August through late December.", category: "farmstand", lat: 38.7100, lng: -120.6380, website: "https://www.applebill.com" },
  { name: "El Dorado County Farmers Market — Placerville", city: "Placerville", note: "The central Placerville farmers market. Seasonal produce, local honey, foothill olive oil, and produce from working farms in the county. Saturday mornings. A reliable source for what's actually in season in El Dorado County, rather than trucked-in produce.", category: "farmstand", lat: 38.7296, lng: -120.7985, website: "https://www.eldoradofarmersmarkets.com" },
  { name: "Gold Hill Vineyard Farmstand", city: "Placerville", note: "The farm-side operation at Gold Hill Vineyard — estate olive oil cold-pressed on-site, vineyard eggs, seasonal vegetables, and a few bottles of wine to take home. Open the same hours as the tasting room. The olive oil is made from trees on the estate and worth bringing home.", category: "farmstand", lat: 38.6979, lng: -120.7000, website: "https://www.goldhillvineyard.com" },
  { name: "Delfino Farms", city: "Camino", note: "Home of Joan's Apple Bakery — one of Apple Hill's most beloved stops. Fresh-baked apple pies, apple butter, cider doughnuts, and seasonal baked goods made on-site at 3205 North Canyon Road. The pies are what people drive up the hill for: made from tree-picked apples, baked throughout the day. Open late August through December. A farm with genuine warmth behind it.", category: "farmstand", lat: 38.7180, lng: -120.6300, website: "https://delfinofarms.com" },
  { name: "El Dorado Orchards", city: "Camino", note: "A classic Apple Hill orchard on North Canyon Road — u-pick apples, fresh-pressed cider, and an on-site farm store carrying fruit, honey, and jams. 2881 N. Canyon Road, Camino. The orchard runs from Galas in late August through the full November crop. Quieter than the Carson Road farms and worth knowing for that reason alone.", category: "farmstand", lat: 38.7173, lng: -120.6292, website: "https://www.eldoradoorchards.com" },
  { name: "American River Cherry Co.", city: "Placerville", note: "Natural-grown (not certified organic) fruit farm on Dias Drive north of Placerville — cherries, blackberries, blueberries, boysenberries, figs, lavender, raspberries, persimmons, and honey from farm hives. U-pick and already-picked. Cherry season in May–June is one of the foothills' great seasonal pleasures. A quieter, more intimate experience than the Apple Hill crowds. Picnic area on site.", category: "farmstand", lat: 38.7390, lng: -120.7815, website: "https://www.americanrivercherryco.com" },
  { name: "24 Carrot Farm", city: "Placerville", note: "CERTIFIED ORGANIC for all crops — apples, pumpkins, and honey from farm hives on Jacquier Road in the Apple Hill area. Chemical-free operation, formerly Willow Pond Farm. A conscientious choice when you want to buy produce from a farm operating with serious agricultural values. Daily 10am–5pm, seasonal.", category: "farmstand", lat: 38.7133, lng: -120.6393, website: "https://www.applebill.com" },
  { name: "South Fork Farm", city: "Coloma", note: "Ten-acre certified organic farm owned by Jaclyn Moyer and Ryan Dorsey, leasing land from the American River Conservancy on a 272-acre property just south of Coloma. Sustainably raised vegetables, bee products, oyster mushrooms, herbs, and flowers. Available through weekly farmers markets and CSA subscription. Farming as land stewardship — one of the source document's top feature candidates.", category: "farmstand", lat: 38.8005, lng: -120.8870, website: "https://edc-farmtrails.org" },
  { name: "Smokey Ridge Farm & Winery", city: "Placerville", note: "Working ranch combining farmstand and winery on Carson Road. Seasonal availability: Apr–Aug and Nov–Dec Sat–Sun 11am–5pm; Sep–Oct Fri–Sun 9am–5pm. A Carson Road corridor stop that blends agricultural and wine production in the tradition of El Dorado County's working farms.", category: "farmstand", lat: 38.7117, lng: -120.6469, website: "https://www.smokeyridgeranch.com" },
  { name: "Argyres Orchard", city: "Camino", note: "U-pick Concord grapes and apples on North Canyon Road — mature trees, some over 70 years old. Taste while picking. A genuinely unusual stop: u-pick grapes in wine country, accessible to anyone who wants to pick their own harvest-season fruit. Open Oct 1–16, weekends only 10am–4pm. Call ahead for ripening dates.", category: "farmstand", lat: 38.7196, lng: -120.6298, website: "https://edc-farmtrails.org" },
  { name: "Larsen Apple Barn", city: "Camino", note: "Founded in the 1860s — the oldest continuously family-owned and operated farm in Apple Hill. On Larsen Drive, the heart of the Apple Hill corridor. Apples harvested from trees that have produced fruit for over 150 years. Open seasonally Labor Day through late November, Mon–Fri and Sunday 9am–5pm. The historical weight of this farm is real: the family has been working this land longer than the Gold Rush is from today.", category: "farmstand", lat: 38.7524, lng: -120.6809, website: "https://www.larsenapplebarn.com" },
  { name: "Sloan Winters Mountain Orchard", city: "Camino", note: "CCOF-certified organic orchard on Snows Road in the Apple Hill area — apples, seasonal produce, and garden crops grown without synthetic inputs. Small operation, Fri–Sun 10am–5pm from August through November. The certification matters: this is one of the few Apple Hill farms operating to full organic standards. Worth seeking out if buying certified is a priority.", category: "farmstand", lat: 38.7040, lng: -120.5820, website: "https://edc-farmtrails.org" },
  { name: "Goldbud Farms", city: "Placerville", note: "One of the few farms in the Apple Hill corridor focused on stone fruit: mountain-grown peaches, nectarines, plums, pluots, and apples, alongside wine grapes on the same property. On Carson Road, open daily 10am–5pm from mid-July through October. The peaches harvested at peak maturity at this elevation have more intensity than valley-floor stone fruit — a genuine seasonal reason to come early in the Apple Hill season before the fall apple crowds arrive.", category: "farmstand", lat: 38.7122, lng: -120.6420, website: "https://goldbudfarms.com" },

  // ── PRODUCERS ─────────────────────────────────────────────────────────────
  { name: "Jack Russell Farm Brewery", city: "Camino", note: "Farm brewery and cider house on American River Trail in Apple Hill — draught ales and hard ciders made from estate-grown apples and barley. The cider operation is central to what this place does, and in fall season they're pressing fresh juice from the orchard. Outdoor seating among the apple trees. The most interesting producer stop on the Apple Hill loop. Open daily in season.", category: "producer", lat: 38.7037, lng: -120.6311, website: "https://www.jackrussellfarm.com" },
  { name: "Fenton Herriott Vineyards", city: "Placerville", note: "Estate winery at the gateway to Apple Hill — the property sits on what was once the old Pony Express Route, giving it a historical layer that most Apple Hill stops lack. Founded in 2002 on volcanic soil in the Northern Sierra Foothills. The naturally balanced growing conditions produce wines the winemaker describes as well-structured yet complex. Open daily 11am–5pm, one of the most accessible tasting rooms in the Apple Hill corridor.", category: "winery", lat: 38.7136, lng: -120.6392, website: "https://www.fentonherriott.com" },
  { name: "Dry Diggings Distillery", city: "El Dorado Hills", note: "Focused on locally produced farm fruit, grains, and wine for vodka, whiskey, brandy, and bourbon. Works with local El Dorado farmers, vintners, and breweries. The tasting room captures Gold Rush-era aesthetic with genuine historical elements — tours and tastings available. The brandy program, drawing on local wine grapes, is the most interesting product for food-and-wine travelers.", category: "producer", lat: 38.6854, lng: -121.0622, website: "https://www.drydiggingsdistillery.com" },
  { name: "Collina di Mela", city: "Placerville", note: "The ONLY certified organic olive oil producer in the Apple Hill Growers Association — a small farm at approximately 2,400 feet elevation on Carson Road. First harvest in November 2009 earned a Gold Medal at the Los Angeles International Extra Virgin Olive Oil Competition. Has continued producing award-winning EVOO since. A quintessential Slow Food producer — single family, specific place, specific craft, with hardware to show for it.", category: "producer", lat: 38.7108, lng: -120.6504, website: "https://edc-farmtrails.org" },

  // ── RESTAURANTS ───────────────────────────────────────────────────────────
  { name: "The Independent Restaurant and Bar", city: "Placerville", note: "Voted Best Overall Restaurant in the Sierra Foothills 11 years in a row — the anchor dining destination for El Dorado County. Rustic-chic dining room with fireplace patio, farm-to-table New American fare: Buttermilk Fried Chicken, CAB Marbled Rib Eye, Lemon Caper Salmon, house-ground Burgers. The truffle macaroni and cheese is a local institution. Craft cocktail program is serious — the 'Sea of Tranquility' is a benchmark. Reservations recommended weekends.", category: "restaurant", lat: 38.7298, lng: -120.7987, website: "https://www.theindependentplacerville.com" },
  { name: "Sweetie Pie's Restaurant & Bakery", city: "Placerville", note: "The beloved breakfast and brunch institution on Main Street — voted Best Breakfast AND Best Brunch in El Dorado County. Massive biscuits, house-baked pastries, eggs done carefully, and the kind of morning cooking that earns its reputation without pretense. Locals queue for it. Plan to wait on weekends. 577 Main St. Opens early.", category: "restaurant", lat: 38.7291, lng: -120.7975, website: "https://sweetiepiesplacerville.com" },
  { name: "Bricks Eats & Drinks", city: "Placerville", note: "The neighborhood anchor at 482 Main Street — American cooking done without fanfare, strong burger program, good local beer selection, and a room that fills up for good reason. Not a tourist destination; a place locals eat. Consistently good, honestly priced, unpretentious. If you're spending a day in Placerville, this is a reliable lunch stop.", category: "restaurant", lat: 38.7295, lng: -120.7978, website: "https://www.bricksonmainstreet.com" },
  { name: "Poor Red's Bar-B-Q", city: "El Dorado", note: "A Gold Rush-era landmark on El Dorado Road that has been serving barbecue and stiff drinks since 1945. The Golden Cadillac cocktail is a California institution. Honest, unpretentious, and exactly what it has always been. Not a destination for the food — a destination for what it is: eighty-plus years of foothill hospitality. Open for lunch and dinner.", category: "restaurant", lat: 38.6745, lng: -120.8620, website: "https://www.poorredsbarbq.com" },
  { name: "Amore Mio Italian Bistro", city: "Placerville", note: "Italian fusion with a devoted local following at 451 Main St. The Piemontese Bagna Cauda flatbread — crispy outside, doughy inside — is described by regulars as the best flatbread in El Dorado County, without hyperbole. Earns word-of-mouth the old-fashioned way: by being genuinely good and not overextending.", category: "restaurant", lat: 38.7294, lng: -120.7982, website: "https://amoremioitalianbistro.com" },
  { name: "Enchanted Forest Dining Experience", city: "Placerville", note: "Reservation-only, immersive European dining experience — four-course fondue dinners in a themed setting. Best suited for a slow, celebratory evening. Genuinely unusual and memorable. Book via OpenTable; this is the kind of dinner that works better when you don't know exactly what to expect going in.", category: "restaurant", lat: 38.7289, lng: -120.7972, website: "https://www.exploretock.com" },
  { name: "Henry's Steakhouse", city: "Placerville", note: "Upscale steakhouse inside Red Hawk Casino at 1 Red Hawk Pkwy — leather seating, wood-detailed interiors, dedicated professional service. Book the dining room directly for the full sit-down experience. The most composed dinner option in El Dorado County when the winery lunch calls for a proper follow-through.", category: "restaurant", lat: 38.7210, lng: -120.7648, website: "https://www.redhawkcasino.com/dining/henrys" },
  { name: "Sienna Restaurant", city: "El Dorado Hills", note: "Ranked #1 of 52 restaurants in El Dorado Hills on TripAdvisor — the go-to upscale dinner in the valley-side part of the county. Modern American grill with fresh seafood, premium steaks, and seasonal chef-driven dishes. A reliable destination for a properly composed meal before or after time in wine country, without driving all the way to Placerville. 1006 White Rock Rd, El Dorado Hills Town Center.", category: "restaurant", lat: 38.6720, lng: -121.0550, website: "https://siennarestaurants.com" },
  { name: "Milestone Restaurant & Cocktail Bar", city: "El Dorado Hills", note: "Contemporary seasonal New American in El Dorado Hills Town Center — locally sourced ingredients and a menu that changes with what's available in the region. Wine and craft cocktail program with a patio overlooking the water. The farm-to-table approach here is genuine, not performative. A solid dinner stop for wine country visitors spending time in the county's valley end. 4359 Town Center Blvd.", category: "restaurant", lat: 38.6732, lng: -121.0555, website: "https://www.milestoneedh.com" },
  { name: "Argonaut Coffee & Provisions", city: "Coloma", note: "Inside Marshall Gold Discovery State Historic Park on Hwy 49 — a café under new ownership that keeps its farm-to-fork mission intact. Organic and locally sourced ingredients, with Bee Love Farms (one of California's oldest pioneer farms) supplying heirloom greens, tomatoes, edible flowers, and fruit. Overlooks the American River. Dog-friendly patio, espresso bar, breakfast and lunch. One of the few dining destinations in El Dorado County that pairs a significant food story with a genuinely beautiful setting.", category: "restaurant", lat: 38.7978, lng: -120.8890, website: "https://www.argonautcafe.com" },
  { name: "Pure Gold Vine Bistro", city: "Somerset", note: "A farm-to-fork bistro in the heart of the Fair Play wine country on Grizzly Flat Road at Mt. Aukum — Executive Chef Lisa's kitchen sources fresh, seasonal produce locally and pours many Sierra Foothill wines. Open Thu–Sun (dinner nightly, brunch Sat–Sun). The best option for a sit-down meal during a day of Fair Play AVA tasting room visits, without driving back down to Placerville.", category: "restaurant", lat: 38.5430, lng: -120.7060, website: "https://www.puregoldvinebistro.com" },
  { name: "Annabelle's Chocolate Lounge", city: "El Dorado", note: "Award-winning artisan chocolate shop and wine bar on Pleasant Valley Road — the same road that leads to Narrow Gate Vineyards. Seventy-five varieties of chocolate, all made without waxes or preservatives. The wine-and-chocolate flight pairs four El Dorado and Amador County wines with chocolates and tasting notes. Open Mon–Sat 11am–6pm. The kind of stop that earns a cult following for doing one thing very well.", category: "producer", lat: 38.6710, lng: -120.8220, website: "https://www.annabelleschocolate.com" },
];

// ─── Seed logic ──────────────────────────────────────────────────────────────

async function correctData() {
  // Fix city values for entries that were seeded with wrong city
  const cityCorrections: { name: string; city: string }[] = [
    { name: "Holly's Hill Vineyards", city: "Placerville" },
    { name: "Narrow Gate Vineyards", city: "Placerville" },
  ];
  for (const { name, city } of cityCorrections) {
    await db
      .update(markersTable)
      .set({ city })
      .where(eq(markersTable.name, name));
  }
}

export async function seedMarkers() {
  try {
    logger.info("Starting marker seed check...");

    // Remove entries that are no longer in the curated list
    if (REMOVED_FROM_SEED.length > 0) {
      const deleted = await db
        .delete(markersTable)
        .where(inArray(markersTable.name, REMOVED_FROM_SEED))
        .returning({ name: markersTable.name });
      if (deleted.length > 0) {
        logger.info(`Removed ${deleted.length} markers: ${deleted.map(d => d.name).join(", ")}`);
      }
    }

    const [{ total }] = await db
      .select({ total: count() })
      .from(markersTable);

    if (Number(total) === 0) {
      logger.info("Empty database — seeding all markers...");
      await db.insert(markersTable).values(SEED_DATA);
      logger.info(`Seeded ${SEED_DATA.length} markers`);
    } else {
      // Upsert: add any new markers not yet in the DB
      const existingNames = await db
        .select({ name: markersTable.name })
        .from(markersTable);
      const existingSet = new Set(existingNames.map(r => r.name));
      const newEntries = SEED_DATA.filter(m => !existingSet.has(m.name));
      if (newEntries.length > 0) {
        await db.insert(markersTable).values(newEntries);
        logger.info(`Added ${newEntries.length} new markers`);
      } else {
        logger.info(`Database has ${total} markers — nothing new to seed`);
      }
    }

    await correctData();
  } catch (err) {
    logger.error({ err }, "Seed failed");
  }
}
